### ISSUE TITLE
大佬，mikManager无法启动，

### ISSUE THREAD

**Issue by yxbbing123** [dqzg12300/MikManager#1]
2022-03-18 14:23:18.237 7653-7653/? E/.mik.mikmanage: Unknown bits set in runtime_flags: 0x8000
2022-03-18 14:23:18.831 7653-7653/com.mik.mikmanager E/mikrom: initConfig config:
2022-03-18 14:23:18.832 7653-7653/com.mik.mikmanager E/mikrom: initConfig err:Attempt to invoke interface method 'java.lang.String android.app.IMikRom.readFile(java.lang.String)' on a null object reference
2022-03-18 14:23:18.832 7653-7653/com.mik.mikmanager E/mikrom: loadGadget enter package:com.mik.mikmanager
2022-03-18 14:23:18.834 7653-7653/com.mik.mikmanager E/mikrom: m1 build shouldMikRom processName:com.mik.mikmanager
2022-03-18 14:23:18.835 7653-7653/com.mik.mikmanager E/mikrom: shouldMikRom processName:com.mik.mikmanager res:false
2022-03-18 14:23:19.444 7653-7653/com.mik.mikmanager E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mik.mikmanager, PID: 7653
    java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String android.app.IMikRom.readFile(java.lang.String)' on a null object reference
        at com.mik.mikmanager.ui.home.HomeFragment.initData(HomeFragment.java:135)
        at com.mik.mikmanager.ui.home.HomeFragment.onCreateView(HomeFragment.java:76)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2698)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:320)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1187)
        at androidx.fragment.app.FragmentManager.addAddedFragments(FragmentManager.java:2224)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1997)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1953)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2629)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2577)
        at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2722)
        at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:346)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1188)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)

**Comment by yxbbing123** [comment]
mikrom 我编译的是user版本，跟这个没关系吧！

**Comment by yxbbing123** [comment]
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
D/mikrom: getiMikRom binder is null
E/mikrom: initConfig config:
D/mikrom: getiMikRom binder is null
E/mikrom: initConfig err:Attempt to invoke interface method 'java.lang.String android.app.IMikRom.readFile(java.lang.String)' on a null object reference
E/mikrom: loadGadget enter package:com.mik.mikmanager
E/mikrom: m1 build shouldMikRom processName:com.mik.mikmanager
    shouldMikRom processName:com.mik.mikmanager res:false

**Comment by dqzg12300** [comment]
> mikrom 我编译的是user版本，跟这个没关系吧！

没有关系的。这种问题是没找到我的服务。adb shell然后service list｜grep mikrom看能找到服务不。没有的话说明你没刷好或者编译的有问题。编译的时候要make update-api j8，然后再make

**Comment by yxbbing123** [comment]
查看服务好像有 mikrom
blueline:/ $ service list|grep mikrom
115     mikrom: [android.app.IMikRom]
blueline:/ $

**Comment by dqzg12300** [comment]
哦。你selinux的配置没修改好。缺少find权限。你可以搜索selinux日志看一下。

**Comment by dqzg12300** [comment]
修复的文件已经提交。你可以重新拉取编译一下。或者看文章的介绍自己修改下。
